image: docker:latest
services:
- docker:dind

stages:
- build
- release

variables:
  RELEASE_IMAGE: txt-bot-and-server:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t txt-bot-and-server:latest .
    - docker push https://gitlab.com/paxterya.com/txt-bot-and-server:latest
