image: docker:latest
services:
- docker:dind

stages:
- build
- release

variables:
  RELEASE_IMAGE: txt-bot-and-server:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.com

build:
  stage: build
  script:
    - docker build --pull -t txt-bot-and-server:latest .
    - docker push $RELEASE_IMAGE
