image: docker:latest
services:
- docker:dind

stages:
- build

build:
  stage: build
  script:
    - docker build --pull -t txt-bot-and-server:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push txt-bot-and-server:latest
