version: '3.1'

services:
  node:
    image: registry.gitlab.com/paxterya/txt-bot-and-server:2021-04-09-backend-typescript
    restart: always
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - "./mc_stats:/srv/txt_bot_and_server/mc_stats"
      - "./config.js:/srv/txt_bot_and_server/config.js"
    links:
      - mongo
    networks:
      - txt_bot_and_server
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: oeignoengoergeoing
      MONGO_INITDB_ROOT_PASSWORD: MB4NLYqp4bu7thdP8ct3vTjcYdG33VXB3yHMR3HJiT3AkBVqFMfpGBt4RPBbDgv3
    volumes:
      - "/tmp/data:/data/db"
    networks:
     - txt_bot_and_server
  frontend:
    image: registry.gitlab.com/paxterya/txt-bot-and-server/nuxt_frontend:master
    restart: always
    links:
      - node
    networks:
      - txt_bot_and_server
networks:
  txt_bot_and_server:
    driver: "bridge"